# Generated by Django 5.0.6 on 2024-07-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='file',
            name='unique_file_name',
        ),
    ]
