# Generated by Django 5.0.6 on 2024-07-24 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_remove_file_unique_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='icon',
            field=models.ImageField(default='icons/default_icon.png', upload_to='icons/'),
        ),
    ]
