# Generated by Django 5.0.6 on 2024-07-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='icon',
        ),
    ]
